apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
spec:
  type: NodePort
  ports:
    - port: {{.Values.port}}
      targetPort: {{.Values.port}} #port used, need to be declared as an environment variable
      protocol: TCP
      name: http
  selector:
    app: {{.Values.name}}-deployment
